// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../lib/sources/base.js', ['zz.routers'], [], false);
goog.addDependency('../../../../../../lib/sources/enums/baseclientconstant.js', ['zz.routers.enums.BaseClientConstant'], ['goog.events'], false);
goog.addDependency('../../../../../../lib/sources/enums/eventtype.js', ['zz.routers.enums.EventType'], ['goog.events'], false);
goog.addDependency('../../../../../../lib/sources/events/routed.js', ['zz.routers.events.Routed'], ['zz.events.BaseEvent', 'zz.routers.enums.EventType'], false);
goog.addDependency('../../../../../../lib/sources/services/baseclientrouter.js', ['zz.routers.services.BaseClientRouter'], ['goog.History', 'goog.Timer', 'goog.array', 'goog.dom', 'goog.events', 'goog.history.EventType', 'goog.history.Html5History', 'goog.object', 'goog.string', 'zz.routers.enums.BaseClientConstant', 'zz.routers.events.Routed', 'zz.services.BaseService'], false);
goog.addDependency('../../../../../../node_modules/zz.events/lib/sources/base.js', ['zz.events'], [], false);
goog.addDependency('../../../../../../node_modules/zz.events/lib/sources/events/baseevents.js', ['zz.events.BaseEvent'], ['goog.events.Event'], false);
goog.addDependency('../../../../../../node_modules/zz.services/lib/sources/base.js', ['zz.services'], [], false);
goog.addDependency('../../../../../../node_modules/zz.services/lib/sources/services/baseservice.js', ['zz.services.BaseService'], [], false);
